---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Renovate"

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: Dry Run
        default: "false"
        required: false
      autodiscover_filter:
        description: "Autodiscover filter"
        default: "*"
        required: false
      cache:
        description: Use Renovate cache from GitHub repo's cache?
        type: choice
        default: "enabled"
        options:
          - enabled
          - disabled
          - reset
      logLevel:
        description: Log Level
        default: debug
        required: false
      version:
        description: Renovate version
        default: latest
        required: false
  schedule:
    - cron: "0 * * * *" # Every hour

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@af35edadc00be37caa72ed9f3e6d5f7801bfdf09 # v1.11.7
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_PRIVATE_KEY }}"
          owner: ${{ github.repository_owner }}

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - name: Renovate Cache
        id: renovate-cache
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        if: github.event.inputs.cache != 'disabled'
        continue-on-error: true
        with:
          path: /tmp/renovate/cache/renovate/repository
          key: renovate-cache-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            renovate-cache-${{ runner.os }}

      - name: Set cache folder permissions
        shell: bash
        run: |
          # chown /tmp/renovate due to cache permissions
          # UID from https://github.com/renovatebot/renovate/blob/9c999fb13e8746830a0c163bad9c244b0b926c6a/tools/docker/Dockerfile#L114
          mkdir -p /tmp/renovate
          sudo chown -R 12021:$(id -g) /tmp/renovate

      - name: Renovate
        uses: renovatebot/github-action@08ed9fa83e24bfe6222557f9e221395c57972127 # v41.0.16
        env:
          LOG_LEVEL: "${{ inputs.logLevel || 'debug' }}"
          RENOVATE_DRY_RUN: "${{ inputs.dryRun == true }}"
          RENOVATE_AUTODISCOVER: true
          RENOVATE_AUTODISCOVER_FILTER: ${{ github.repository_owner }}/${{ inputs.autodiscover_filter || '*' }}
          RENOVATE_PLATFORM: github
          RENOVATE_PLATFORM_COMMIT: true
          RENOVATE_REPOSITORY_CACHE: ${{ github.event.inputs.cache }}
          RENOVATE_INTERNAL_CHECKS_FILTER: strict
        with:
          token: "${{ steps.app-token.outputs.token }}"
